# Site settings

title: "William Oliveira: Programação, JavaScript, Carreira e inclusão"
page_title: William Oliveira, front-end software engineer
subtitle: Pintor de software
description: Mentoria, Carreira em programação, JavaScript, Nodejs, Git, GitHub, Open Source, inclusão e diversidade - Da periferia pro mundo
author: William Oliveira
timezone: America/Sao_Paulo
baseurl: "" # the subpath of your site, e.g. /blog
url: https://woliveiras.com.br
language: "pt-br"
paginate: 5 # Number of posts on each page
paginate_path: "/page/:num" # links format for pagination
date_format: "%d/%m/%Y"  # dateformat of reading list, post date, and more
permalink: /posts/:title/ # use to url friendly
display-author-front-page: false # True if you need show author name and site on home page
display-author-post-page: false # Very usual for guest posts and the infos of author are writen in header of post.md, by default show infos of user settings
google_analytics: UA-25964646-1

# Useful for translating into other languages.

var_on_the_web: Na internet
var_read: Continuar a leitura...
var_newer: Novos
var_older: Antigos
var_next_post: Próximo
var_previous_post: Anterior
var_less_than_a_minute_read: < 1 min leitura
var_min_read: min leitura # Text after reading time. Example: 5 min read.
var_post_by: Escrito por
var_guest_post_by: Guest post by
var_your_email: Email
var_your_message: Mensagem
var_page_indicator: Página
var_page_indicator_separator: de

# User settings

author: woliveiras # put your name or a name of principal author of site/blog
email: williamozsouza@gmail.com
twitter_username: etc_william
gplus_username: +WilliamOliveiraS
github_username:  woliveiras
linkedin_username: william-oliveira
disqus_shortname: woliveiras

# Build settings

# incremental: true
post_images: /images/posts/
site_images: /images/
markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml
feed:
  path: atom.xml
  categories:
    - carreira
    - programação
    - tecnologia
    - updates
    - news
sass:
  sass_dir: _sass
  style: compressed
collections:
  categoria:
    output: true
compress_images:
  svgo: false
  images_path: "images/**/*.{gif,png,jpg,jpeg}"
  jpegrecompress:
    allow_lossy: true
    quality: 2
    max_quality: 60
imageoptim:
  svgo: false

defaults:
  - scope:
      path: ""
      type: categoria
    values:
      layout: "category"
  - scope:
      path: ""
      type: posts
    values:
      is_post: true

# exclude files if no need build
exclude: [
    'package.json',
    'node_modules',
    'README.md',
    'LICENSE',
    'Gemfile',
    'Gemfile.lock'
]

# plugins
plugins:
    - amp-jekyll
    - jemoji
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-gist
    - jekyll-redirect-from
    - jekyll-compress-images
