[[redirects]]
  from = "/my-precious-links"
  to = "https://mypreciouslinks.woliveiras.dev"
  
[[redirects]]
  from = "/front-end-career"
  to = "https://frontendcareer.woliveiras.dev/"

[[redirects]]
  from = "/vimparanoobs"
  to = "https://leanpub.com/vimparanoobs/"
