# Site settings

title: William Oliveira - Desenvolvedor de Software
subtitle: Pintor de software
description: Um blog sobre Desenvolvimento de Software, Front End, HTML, CSS, Sass, Stylus, JavaScript, Nodejs, Linux até Ferramentas e Metodologias de Desenvolvimento para iniciantes ou avançados!
author: William de Oliveira
timezone: America/Sao_Paulo
baseurl: "" # the subpath of your site, e.g. /blog
url: https://woliveiras.com.br
language: "pt-br"
paginate: 5 # Number of posts on each page
paginate_path: "/page/:num" # links format for pagination
date_format: "%b %-d, %Y"  # dateformat of reading list, post date, and more
permalink: /posts/:title/ # use to url friendly
display-author-front-page: # True if you need show author name and site on home page
display-author-post-page: true # Very usual for guest posts and the infos of author are writen in header of post.md, by default show infos of user settings

# Useful for translating into other languages.

var_on_the_web: On the web
var_read: Continue...
var_newer: Newers
var_older: Olders
var_next_post: Next
var_previous_post: Previous
var_less_than_a_minute_read: < 1 min read
var_min_read: min read # Text after reading time. Example: 5 min read.
var_post_by: Writed by
var_guest_post_by: Guest post by
var_your_email: Your mail
var_your_message: Your message
var_page_indicator: Page
var_page_indicator_separator: of

# User settings

author: woliveiras # put your name or a name of principal author of site/blog
email: williamozsouza@gmail.com
twitter_username: w_oliveiras
github_username:  woliveiras
# gplus_username:  dunders
disqus_shortname: woliveiras

# Navigation menu
nav-menu:
  - title: Home
    url: /
  - title: Sobre
    url: /sobre
  - title: Categorias
    url: /categorias

# Footer menu

footer-menu:
  - title: Mentoria em programação
    url: /mentoria
  - title: Meus Links
    url: /my-precious-links
  - title: Pair programming
    url: /pair-programming
  - title: Quero me tornar frontend
    url: /front-end-career
  - title: Me pagar um café
    url: /donation
  - title: Portfólio
    url: /portfolio
  - title: Curriculum
    url: https://www.linkedin.com/in/william-oliveira/

# Build settings

incremental: true
markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml
feed:
  path: atom.xml
sass:
  sass_dir: _sass
  style: compressed

## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: [
    'package.json',
    'node_modules',
    'README.md',
    'LICENSE',
    'Gemfile',
    'Gemfile.lock'
]

# Gems
gems: [
    jekyll-paginate,
    jekyll-sitemap,
    jekyll-feed,
    jekyll-seo-tag
]
